services:
  portfolio:
    build: ./apps/portfolio
    container_name: portfolio
    ports:
      - "3000:80"
    restart: unless-stopped

  app2:
    build: ./apps/app2
    container_name: app2
    ports:
      - "3001:80"
    restart: unless-stopped
